Repository ktorio/ktor, pull requests merged in 2020-11, with the labels that each got.

#2196 KTOR-1298 Fix hanging HEAD response with Netty HTTP/2
  ktor-server/ktor-server-netty/jvm/src/io/ktor/server/netty/NettyApplicationCallHandler.kt
  ktor-server/ktor-server-netty/jvm/src/io/ktor/server/netty/cio/NettyResponsePipeline.kt
  ktor-server/ktor-server-netty/jvm/src/io/ktor/server/netty/http2/NettyHttp2ApplicationResponse.kt
  ktor-server/ktor-server-netty/jvm/test/io/ktor/tests/server/netty/NettyEngineTest.kt
Labels: Server, bug

#2193 Fix IncorrectDereferenceException when using HttpClient on Dispatchers.Default
  ktor-client/ktor-client-tests/posix/test/io/ktor/client/tests/HttpClientFreezingTest.kt
  ktor-http/common/src/io/ktor/http/HeaderValueWithParameters.kt
Labels: Client

#2208 Cy/ktlint
  .editorconfig
  build.gradle
  gradle.properties
  gradle/codestyle.gradle
Labels: Housekeeping

#2209 KTOR-1338 Fix formatting in ktor-server-core
  ktor-server/ktor-server-core/jvm/src/io/ktor/application/ApplicationCall.kt
  ktor-server/ktor-server-core/jvm/src/io/ktor/application/ApplicationCallPipeline.kt
  ktor-server/ktor-server-core/jvm/src/io/ktor/application/ApplicationFeature.kt
  ktor-server/ktor-server-core/jvm/src/io/ktor/config/HoconApplicationConfig.kt
  ktor-server/ktor-server-core/jvm/src/io/ktor/config/MapApplicationConfig.kt
  ktor-server/ktor-server-core/jvm/src/io/ktor/features/AutoHeadResponse.kt
  ktor-server/ktor-server-core/jvm/src/io/ktor/features/CallId.kt
  ktor-server/ktor-server-core/jvm/src/io/ktor/features/CallLogging.kt
  ktor-server/ktor-server-core/jvm/src/io/ktor/features/Compression.kt
  ktor-server/ktor-server-core/jvm/src/io/ktor/features/ConditionalHeaders.kt
  ktor-server/ktor-server-core/jvm/src/io/ktor/features/ContentNegotiation.kt
  ktor-server/ktor-server-core/jvm/src/io/ktor/features/DefaultHeaders.kt
  ktor-server/ktor-server-core/jvm/src/io/ktor/features/DoubleReceive.kt
  ktor-server/ktor-server-core/jvm/src/io/ktor/features/MultipleRangeWriter.kt
  ktor-server/ktor-server-core/jvm/src/io/ktor/features/OriginConnectionPoint.kt
  ktor-server/ktor-server-core/jvm/src/io/ktor/features/PartialContent.kt
  ktor-server/ktor-server-core/jvm/src/io/ktor/features/StatusPages.kt
  ktor-server/ktor-server-core/jvm/src/io/ktor/http/HttpDate.kt
  ktor-server/ktor-server-core/jvm/src/io/ktor/http/HttpDateJvm.kt
  ktor-server/ktor-server-core/jvm/src/io/ktor/http/LinkHeader.kt
  ktor-server/ktor-server-core/jvm/src/io/ktor/http/content/CachingOptionsJvm.kt
  ktor-server/ktor-server-core/jvm/src/io/ktor/http/content/DefaultTransform.kt
  ktor-server/ktor-server-core/jvm/src/io/ktor/http/content/JarFileContent.kt
  ktor-server/ktor-server-core/jvm/src/io/ktor/http/content/LastModifiedJavaTime.kt
  ktor-server/ktor-server-core/jvm/src/io/ktor/http/content/LocalFileContent.kt
  ktor-server/ktor-server-core/jvm/src/io/ktor/http/content/StaticContent.kt
  ktor-server/ktor-server-core/jvm/src/io/ktor/http/content/StaticContentResolution.kt
  ktor-server/ktor-server-core/jvm/src/io/ktor/request/ApplicationReceiveFunctions.kt
  ktor-server/ktor-server-core/jvm/src/io/ktor/request/ApplicationRequestProperties.kt
  ktor-server/ktor-server-core/jvm/src/io/ktor/response/ApplicationResponse.kt
  ktor-server/ktor-server-core/jvm/src/io/ktor/response/ApplicationResponseFunctions.kt
  ktor-server/ktor-server-core/jvm/src/io/ktor/response/ApplicationResponseProperties.kt
  ktor-server/ktor-server-core/jvm/src/io/ktor/response/ApplicationSendPipeline.kt
  ktor-server/ktor-server-core/jvm/src/io/ktor/response/DefaultResponsePushBuilder.kt
  ktor-server/ktor-server-core/jvm/src/io/ktor/response/ResponseCookies.kt
  ktor-server/ktor-server-core/jvm/src/io/ktor/response/ResponseHeaders.kt
  ktor-server/ktor-server-core/jvm/src/io/ktor/response/ResponsePushBuilder.kt
  ktor-server/ktor-server-core/jvm/src/io/ktor/routing/HostsRoutingBuilder.kt
  ktor-server/ktor-server-core/jvm/src/io/ktor/routing/RouteSelector.kt
  ktor-server/ktor-server-core/jvm/src/io/ktor/routing/Routing.kt
  ktor-server/ktor-server-core/jvm/src/io/ktor/routing/RoutingBuilder.kt
  ktor-server/ktor-server-core/jvm/src/io/ktor/routing/RoutingPath.kt
  ktor-server/ktor-server-core/jvm/src/io/ktor/routing/RoutingResolve.kt
  ktor-server/ktor-server-core/jvm/src/io/ktor/routing/RoutingResolveTrace.kt
  ktor-server/ktor-server-core/jvm/src/io/ktor/sessions/JavaTimeMigration.kt
  ktor-server/ktor-server-core/jvm/src/io/ktor/sessions/SessionSerializerReflection.kt
  ktor-server/ktor-server-core/jvm/src/io/ktor/sessions/SessionStorageMemory.kt
  ktor-server/ktor-server-core/jvm/src/io/ktor/sessions/SessionTrackerByValue.kt
  ktor-server/ktor-server-core/jvm/src/io/ktor/sessions/SessionTransport.kt
  ktor-server/ktor-server-core/jvm/src/io/ktor/sessions/SessionTransportTransformerDigest.kt
  ktor-server/ktor-server-core/jvm/src/io/ktor/sessions/SessionTransportTransformerEncrypt.kt
  ktor-server/ktor-server-core/jvm/src/io/ktor/sessions/SessionTransportTransformerMessageAuthentication.kt
  ktor-server/ktor-server-core/jvm/src/io/ktor/sessions/Sessions.kt
  ktor-server/ktor-server-core/jvm/src/io/ktor/sessions/SessionsBuilder.kt
  ktor-server/ktor-server-core/jvm/src/io/ktor/util/ConversionService.kt
  ktor-server/ktor-server-core/jvm/src/io/ktor/util/Parameters.kt
  ktor-server/ktor-server-core/jvm/src/io/ktor/util/Paths.kt
  ktor-server/ktor-server-core/jvm/src/io/ktor/util/URLBuilder.kt
Labels: Housekeeping

#2207 Reformat ktor-http to conform to ktlint
  ktor-http/common/src/io/ktor/http/CacheControl.kt
  ktor-http/common/src/io/ktor/http/Codecs.kt
  ktor-http/common/src/io/ktor/http/Cookie.kt
  ktor-http/common/src/io/ktor/http/CookieUtils.kt
  ktor-http/common/src/io/ktor/http/FileContentType.kt
  ktor-http/common/src/io/ktor/http/HeaderValueWithParameters.kt
  ktor-http/common/src/io/ktor/http/Headers.kt
  ktor-http/common/src/io/ktor/http/HttpHeaderValueParser.kt
  ktor-http/common/src/io/ktor/http/HttpHeaders.kt
  ktor-http/common/src/io/ktor/http/HttpMessageProperties.kt
  ktor-http/common/src/io/ktor/http/HttpProtocolVersion.kt
  ktor-http/common/src/io/ktor/http/HttpUrlEncoded.kt
  ktor-http/common/src/io/ktor/http/LinkHeader.kt
  ktor-http/common/src/io/ktor/http/Parameters.kt
  ktor-http/common/src/io/ktor/http/Query.kt
  ktor-http/common/src/io/ktor/http/URLBuilder.kt
  ktor-http/common/src/io/ktor/http/URLParser.kt
  ktor-http/common/src/io/ktor/http/URLProtocol.kt
  ktor-http/common/src/io/ktor/http/auth/HttpAuthHeader.kt
  ktor-http/common/src/io/ktor/http/content/CachingOptions.kt
  ktor-http/common/src/io/ktor/http/content/Multipart.kt
  ktor-http/common/src/io/ktor/http/content/OutgoingContent.kt
  ktor-http/common/src/io/ktor/http/parsing/GrammarBuilder.kt
  ktor-http/common/src/io/ktor/http/websocket/Utils.kt
Labels: Housekeeping

#2217 KTOR-1363 Upgrade Netty to 4.1.54.Final
  gradle.properties
Labels: Housekeeping, Server

#2218 KTOR-905 Fix Netty HTTP 400 BadRequest response
  ktor-server/ktor-server-netty/jvm/src/io/ktor/server/netty/NettyApplicationCallHandler.kt
  ktor-server/ktor-server-netty/jvm/src/io/ktor/server/netty/NettyApplicationEngine.kt
  ktor-server/ktor-server-netty/jvm/src/io/ktor/server/netty/NettyApplicationRequest.kt
  ktor-server/ktor-server-netty/jvm/src/io/ktor/server/netty/NettyApplicationResponse.kt
  ktor-server/ktor-server-netty/jvm/src/io/ktor/server/netty/NettyChannelInitializer.kt
  ktor-server/ktor-server-netty/jvm/src/io/ktor/server/netty/http1/NettyHttp1ApplicationRequest.kt
  ktor-server/ktor-server-netty/jvm/src/io/ktor/server/netty/http1/NettyHttp1ApplicationResponse.kt
  ktor-server/ktor-server-test-suites/jvm/src/io/ktor/server/testing/Utils.kt
  ktor-server/ktor-server-test-suites/jvm/src/io/ktor/server/testing/suites/SustainabilityTestSuite.kt
Labels: Server, bug

#2219 KTOR-1367 Handle failure in reading request body
  ktor-client/ktor-client-apache/jvm/src/io/ktor/client/engine/apache/ApacheRequestProducer.kt
  ktor-client/ktor-client-okhttp/jvm/src/io/ktor/client/engine/okhttp/OkUtils.kt
  ktor-client/ktor-client-tests/jvm/src/io/ktor/client/tests/HttpClientTest.kt
  ktor-http/ktor-http-cio/common/src/io/ktor/http/cio/ChunkedTransferEncoding.kt
  ktor-io/common/src/io/ktor/utils/io/internal/SequentialCopyTo.kt
  ktor-io/jvm/src/io/ktor/utils/io/ByteBufferChannel.kt
Labels: Client, bug

#2220 KTOR-1371 Fix formatting in ktor-server-cio to conform to ktlint
  ktor-server/ktor-server-cio/jvm/src/io/ktor/server/cio/CIO.kt
  ktor-server/ktor-server-cio/jvm/src/io/ktor/server/cio/CIOApplicationEngine.kt
  ktor-server/ktor-server-cio/jvm/src/io/ktor/server/cio/CIOApplicationResponse.kt
  ktor-server/ktor-server-cio/jvm/src/io/ktor/server/cio/HttpServer.kt
  ktor-server/ktor-server-cio/jvm/test/io/ktor/tests/server/cio/CIOHttpClientTest.kt
  ktor-server/ktor-server-cio/jvm/test/io/ktor/tests/server/cio/RAWExample.kt
Labels: Housekeeping

#2205 KTOR-1127 Rewrite timeout impl for CIO
  ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/HttpTimeoutTest.kt
  ktor-network/jvm/src/io/ktor/network/sockets/CIOReader.kt
  ktor-network/jvm/src/io/ktor/network/sockets/CIOWriter.kt
  ktor-network/jvm/src/io/ktor/network/util/Utils.kt
  ktor-network/jvm/test/io/ktor/network/util/StartTimeoutTest.kt
  ktor-utils/common/src/io/ktor/util/date/Date.kt
  ktor-utils/js/src/io/ktor/util/date/DateJs.kt
  ktor-utils/jvm/src/io/ktor/util/date/DateJvm.kt
  ktor-utils/posix/src/io/ktor/util/date/DateNative.kt
Labels: Server

#2215 KTOR-1358 Propagate parentCoroutineContext to handlers
  ktor-server/ktor-server-netty/jvm/src/io/ktor/server/netty/NettyApplicationEngine.kt
  ktor-server/ktor-server-servlet/jvm/src/io/ktor/server/servlet/ServletApplicationEngine.kt
  ktor-server/ktor-server-test-suites/jvm/src/io/ktor/server/testing/suites/HttpServerTestSuite.kt
  ktor-server/ktor-server-tomcat/jvm/src/io/ktor/server/tomcat/TomcatApplicationEngine.kt
Labels: Server, bug
