Repository ktorio/ktor, pull requests merged in 2021-01, with the labels that each got.

#2283 KTOR-370 Fix status code response accepting any numeric value (#1882)
  ktor-http/ktor-http-cio/common/src/io/ktor/http/cio/HttpParser.kt
  ktor-http/ktor-http-cio/common/test/io/ktor/tests/http/cio/HttpParserTest.kt
Labels: Server

#2288 KTOR - 378 Fix request/response accepting empty header name (#1868)
  ktor-http/ktor-http-cio/common/src/io/ktor/http/cio/HttpParser.kt
  ktor-http/ktor-http-cio/common/test/io/ktor/tests/http/cio/HttpParserTest.kt
Labels: Server

#2287 KTOR-1615 fix single slash routing
  ktor-client/ktor-client-tests/jvm/src/io/ktor/client/tests/utils/tests/Cookies.kt
  ktor-client/ktor-client-tests/jvm/src/io/ktor/client/tests/utils/tests/Headers.kt
  ktor-client/ktor-client-tests/jvm/src/io/ktor/client/tests/utils/tests/Redirect.kt
  ktor-server/ktor-server-core/jvm/src/io/ktor/routing/RouteSelector.kt
  ktor-server/ktor-server-core/jvm/src/io/ktor/routing/Routing.kt
  ktor-server/ktor-server-core/jvm/src/io/ktor/routing/RoutingBuilder.kt
  ktor-server/ktor-server-core/jvm/src/io/ktor/routing/RoutingResolve.kt
  ktor-server/ktor-server-core/jvm/test/io/ktor/tests/routing/RouteSelectorTest.kt
  ktor-server/ktor-server-tests/jvm/test/io/ktor/tests/server/routing/RoutingBuildTest.kt
  ktor-server/ktor-server-tests/jvm/test/io/ktor/tests/server/routing/RoutingResolveTest.kt
Labels: Server, routing

#2292 KTOR-1615 Fix apidump
  ktor-client/ktor-client-java/api/ktor-client-java.api
  ktor-io/api/ktor-io.api
Labels: Housekeeping, bug

#2298 Update IDEA's project.xml
  .idea/codeStyles/Project.xml
Labels: Housekeeping

#2291 KTOR-1374 Avoid using reserved web socket close reason codes in OkHtt…
  ktor-client/ktor-client-features/ktor-client-websockets/common/test/io/ktor/client/tests/features/WebSocketRemoteTest.kt
  ktor-client/ktor-client-okhttp/jvm/src/io/ktor/client/engine/okhttp/OkHttpWebsocketSession.kt
Labels: Client, bug

#2297 KTOR-378 Fix empty header name diagnostic
  ktor-http/ktor-http-cio/common/src/io/ktor/http/cio/HttpParser.kt
  ktor-http/ktor-http-cio/common/test/io/ktor/tests/http/cio/HttpParserTest.kt
Labels: bug

#2303 KTOR-1374 Avoid using reserved status codes in JS engine
  ktor-client/ktor-client-core/js/src/io/ktor/client/features/websocket/JsWebSocketSession.kt
Labels: Client, bug

#2305 ~ Make CIO selector do wakeup on close/suspend
  ktor-network/posix/src/io/ktor/network/selector/SelectUtils.kt
  ktor-network/posix/src/io/ktor/network/selector/SignalPoint.kt
  ktor-network/posix/src/io/ktor/network/selector/WorkerSelectorManager.kt
Labels: Native

#2311 KTOR-1661 Fix testEarlyCancellation
  ktor-client/ktor-client-core/jvm/test/HttpClientEngineTest.kt
Labels: Client

#2318 KTOR-1371 Cleanup codestyle in ktor-server
  ktor-features/ktor-serialization/jvm/src/io/ktor/serialization/JsonSupport.kt
  ktor-http/ktor-http-cio/jvm/src/io/ktor/http/cio/Multipart.kt
  ktor-http/ktor-http-cio/jvm/src/io/ktor/http/cio/Pipeline.kt
  ktor-http/ktor-http-cio/jvm/src/io/ktor/http/cio/websocket/DefaultWebSocketSession.kt
  ktor-http/ktor-http-cio/jvm/src/io/ktor/http/cio/websocket/DefaultWebSocketSessionImpl.kt
  ktor-http/ktor-http-cio/jvm/src/io/ktor/http/cio/websocket/Frame.kt
  ktor-http/ktor-http-cio/jvm/src/io/ktor/http/cio/websocket/PingPong.kt
  ktor-http/ktor-http-cio/jvm/src/io/ktor/http/cio/websocket/RawWebSocket.kt
  ktor-http/ktor-http-cio/jvm/src/io/ktor/http/cio/websocket/Serializer.kt
  ktor-http/ktor-http-cio/jvm/src/io/ktor/http/cio/websocket/UtilsJvm.kt
  ktor-http/ktor-http-cio/jvm/src/io/ktor/http/cio/websocket/WebSocketReader.kt
  ktor-http/ktor-http-cio/jvm/src/io/ktor/http/cio/websocket/WebSocketWriter.kt
  ktor-http/ktor-http-cio/jvm/src/io/ktor/server/cio/backend/ServerPipeline.kt
  ktor-http/ktor-http-cio/jvm/src/io/ktor/server/cio/backend/ServerRequestScope.kt
  ktor-server/ktor-server-core/jvm/src/io/ktor/features/CORS.kt
  ktor-server/ktor-server-core/jvm/src/io/ktor/features/HttpsRedirect.kt
  ktor-server/ktor-server-core/jvm/src/io/ktor/routing/RouteSelector.kt
  ktor-server/ktor-server-core/jvm/src/io/ktor/sessions/SessionSerializerReflection.kt
Labels: Housekeeping
